### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by yifanai** [matteo-rizzo/improved-tcc#1]
Hi, thanks for open sourcing your code. Do you have plans to upload the pretrained models to public cloud services (e.g. Google Drive, Dropbox, etc)? It seems that the current download link requires a UBC Sharepoint account.

**Comment by matteo-rizzo** [comment]
Hi! I'm currently uploading the models to Google Drive so that they are accessible to everybody: https://drive.google.com/drive/folders/1WCOL7Ahy_tDCQDvqn0KQqRhv7eukf3jf?usp=sharing

Please note that it should take a few hours since I post this for all models to be online. I will also update the link in the README.

**Comment by yifanai** [comment]
Thank you!
